# Generated by Django 4.2.17 on 2025-04-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_permission_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=20),
        ),
    ]
