# Generated by Django 4.2.17 on 2025-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_city_insertion"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar_images/"),
        ),
    ]
