# Generated by Django 4.2.17 on 2025-01-24 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("gstin", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "active"),
                            ("pending_verification", "Pending in verification"),
                            ("Deactive", "deactive"),
                        ],
                        default="pending_verification",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("clothing_fashion", "Clothing and Fashion"),
                            ("food_beverages", "Food and Beverages"),
                            ("health_beauty", "Health and Beauty"),
                            ("home_furniture", "Home and Furniture"),
                            ("toys_games", "Toys and Games"),
                            ("books_stationery", "Books and Stationery"),
                            ("sports_outdoors", "Sports and Outdoors"),
                            ("automotive", "Automotive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "delivery_charge_per_km",
                    models.IntegerField(
                        default=10,
                        help_text="The delivery charge per kilometer. This amount will be multiplied by the distance (in kilometers) to calculate the total delivery charge for an order.",
                    ),
                ),
                (
                    "platform_fees",
                    models.IntegerField(
                        default=10,
                        help_text="Percentage of the total order amount to be charged as platform fee for this store.",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.city",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("price", models.FloatField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("out_of_stock", "Out of stock"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.store"
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
